name: Sync Branches

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Sync branches after release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: "alpha"
          SOURCE_BRANCH: "main"
        run: |
          git checkout ${TARGET_BRANCH}
          git checkout ${SOURCE_BRANCH}

          has_diff=$( git diff --quiet --exit-code ${SOURCE_BRANCH} ${TARGET_BRANCH} ; echo $? )
          if [[ "${has_diff}" == "0" ]]; then
            echo "no diff between ${SOURCE_BRANCH} and ${DEPLOY_TARGET}, aborting step ..."
            exit 0
          elif [[ "${has_diff}" != "1" ]]; then
            echo 'git diff failed unexpectedly.'
            exit 1
          fi
          
          echo "🚀 Creating pull request from ${SOURCE_BRANCH} to ${TARGET_BRANCH}"

          PR_TITLE="ci: merge ${SOURCE_BRANCH} into ${TARGET_BRANCH}"
          PR_BODY="⚠️ This pull request has been created after a release tag on ${TARGET_BRANCH} an should merge automatically"

          pr_url=$( gh pr create --base ${TARGET_BRANCH} --head ${SOURCE_BRANCH} --title "${PR_TITLE}" --body "${PR_BODY}" --no-maintainer-edit )

          echo "Created pull request ${pr_url} 🚀"

          if [[ -z "${pr_url}" ]]; then
            echo "failed to create pull request unexpectedly."
            exit 1
          fi

          echo "🚀 Merging pull request ${pr_url} using rebase ..."

          gh pr merge ${pr_url} --admin --rebase"

          echo "Pull request merged 🚀"
