name: Sync Branches

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Sync branches after release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: "alpha"
          SOURCE_BRANCH: "main"
        run: |
          has_diff=$( git diff --quiet --exit-code ${SOURCE_BRANCH} ${TARGET_BRANCH} ; echo $? )
          if [[ "${has_diff}" == "0" ]]; then
            echo "no diff between ${SOURCE_BRANCH} and ${DEPLOY_TARGET}, aborting step ..."
            exit 0
          elif [[ "${has_diff}" != "1" ]]; then
            echo 'git diff failed unexpectedly.'
            exit 1
          fi

          echo "🚀 Rebasing ${TARGET_BRANCH} on ${SOURCE_BRANCH}"

          git fetch
          git checkout ${TARGET_BRANCH}
          git rebase origin/${SOURCE_BRANCH}
          git push

          echo "Branch ${TARGET_BRANCH} rebased on ${SOURCE_BRANCH}  🚀"
